web:
  image: pos-frontend
#  volumes:
#    - .:/etc/nginx/conf.d/mysite.template
  ports:
    - "8080:80"
  environment:
    - NGINX_HOST=pos-frontend.com
    - NGINX_PORT=80
    - API_URL=http://pos.backend.io
    - STRIPE_KEY=pk_123123123123123