apiVersion: apps/v1
kind: Deployment                                         #Which Component
metadata:
  name: pos-frontend-deployment                                #Name Deployment
  labels:
    app: pos-frontend
spec:                                                    #Specification for deployment
  replicas: 2                                            #How Many Replicas
  selector:
    matchLabels:
      app: pos-frontend
  template:                                               #Blue print of the pod
    metadata:
      labels:
        app: pos-frontend
    spec:                                                 #Specification for pods
      containers:
        - name: pos-frontend                                     #1 container inside the pod
          image: pos-frontend
          imagePullPolicy: IfNotPresent                         # 7
          ports:
            - containerPort: 8080 # doc port
          env:
            - name: VUE_APP_STRIPE_PK
              valueFrom:
                secretKeyRef:
                  name: pos-backend-secret
                  key: stripe-pk
            - name: VUE_APP_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: pos-backend-configmap
                  key: auth-url
            - name: VUE_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: pos-backend-configmap
                  key: api-url
---
apiVersion: v1
kind: Service
metadata:
  name: pos-frontend-service
spec:
  selector:
    app: pos-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 89 #ServicePort
      targetPort: 8080 #Containerport
      nodePort: 31901


